Repository 22-s/BE, pull requests merged in 2024-12, with the labels that each got.

#45 [Bug] #44 - 퀴즈 목록 조회 시 isInReviewList 반환 수정
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
Labels: :bug: fix, 🐸 하은 작업

#46 [Refactor] #43 -매너 설명서 API 즐겨찾기 여부 추가
  src/main/java/dgu/sw/domain/manner/controller/MannerController.java
  src/main/java/dgu/sw/domain/manner/converter/MannerConverter.java
  src/main/java/dgu/sw/domain/manner/dto/MannerDTO.java
  src/main/java/dgu/sw/domain/manner/service/MannerService.java
  src/main/java/dgu/sw/domain/manner/service/MannerServiceImpl.java
Labels: :recycle: refactor, 🐿️ 영신 작업

#48 [Refactor] #47 - 복습 리스트 조회 시 correct 추가
  src/main/java/dgu/sw/domain/quiz/controller/QuizController.java
  src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
  src/main/java/dgu/sw/domain/quiz/dto/QuizDTO.java
  src/main/java/dgu/sw/domain/quiz/service/QuizService.java
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
Labels: :recycle: refactor, 🐸 하은 작업

#52 [Refactor] #51 - 모든 퀴즈 첫번째 문제 lock 해제
  src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
Labels: :recycle: refactor, 🐸 하은 작업

#56 [Feature] #55 - 이메일 중복 여부 확인 API 구현
  src/main/java/dgu/sw/domain/user/controller/UserController.java
  src/main/java/dgu/sw/domain/user/dto/UserDTO.java
  src/main/java/dgu/sw/domain/user/service/UserService.java
  src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
Labels: ✨ feature, 🐸 하은 작업

#54 [Feature] #53 - 비즈니스 트렌드 크롤링 API 1차 구현
  build.gradle
  src/main/java/dgu/sw/domain/business/entity/Business.java
  src/main/java/dgu/sw/domain/business/entity/BusinessImage.java
  src/main/java/dgu/sw/domain/trend/controller/TrendController.java
  src/main/java/dgu/sw/domain/trend/dto/TrendDTO.java
  src/main/java/dgu/sw/domain/trend/service/TrendService.java
Labels: ✨ feature, 🐿️ 영신 작업

#61 [Bug] #57 - 트렌드 API 로드 시간 줄임
  Dockerfile
  src/main/java/dgu/sw/domain/trend/service/TrendService.java
Labels: :bug: fix, 🐿️ 영신 작업

#63 [Docs] readme 작성
  README.md
Labels: :memo: docs, 🐸 하은 작업
