Repository 22-s/BE, pull requests merged in 2025-03, with the labels that each got.

#93 [Feature] #91 - 퀴즈 기능 확장을 위한 엔티티 수정 및 MockTest 도입
  src/main/java/dgu/sw/domain/quiz/entity/MockTest.java
  src/main/java/dgu/sw/domain/quiz/entity/MockTestQuiz.java
  src/main/java/dgu/sw/domain/quiz/entity/UserQuiz.java
Labels: ✨ feature, 🐸 하은 작업

#94 [Feature] #92 - 퀴즈 메인 페이지 조회 API 구현
  src/main/java/dgu/sw/domain/quiz/controller/QuizController.java
  src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
  src/main/java/dgu/sw/domain/quiz/dto/QuizDTO.java
  src/main/java/dgu/sw/domain/quiz/entity/UserQuiz.java
  src/main/java/dgu/sw/domain/quiz/repository/MockTestRepository.java
  src/main/java/dgu/sw/domain/quiz/repository/UserQuizRepository.java
  src/main/java/dgu/sw/domain/quiz/service/QuizService.java
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
Labels: ✨ feature, 🐸 하은 작업

#96 [Feature] #95 - 어제 푼 퀴즈 조회 API 구현
  src/main/java/dgu/sw/domain/quiz/controller/QuizController.java
  src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
  src/main/java/dgu/sw/domain/quiz/dto/QuizDTO.java
  src/main/java/dgu/sw/domain/quiz/repository/UserQuizRepository.java
  src/main/java/dgu/sw/domain/quiz/service/QuizService.java
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
Labels: ✨ feature, 🐸 하은 작업

#98 [Refactor] #97 - 퀴즈 순차 진행 로직 추가 (이전 퀴즈 풀었는지 확인)
  src/main/java/dgu/sw/domain/quiz/repository/QuizRepository.java
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
Labels: :recycle: refactor, 🐸 하은 작업

#100 [Feature] #99 - 모의고사 관련 API 구현
  src/main/java/dgu/sw/domain/quiz/controller/MockTestController.java
  src/main/java/dgu/sw/domain/quiz/converter/MockTestConverter.java
  src/main/java/dgu/sw/domain/quiz/dto/MockTestDTO.java
  src/main/java/dgu/sw/domain/quiz/entity/MockTest.java
  src/main/java/dgu/sw/domain/quiz/entity/MockTestQuiz.java
  src/main/java/dgu/sw/domain/quiz/repository/MockTestQuizRepository.java
  src/main/java/dgu/sw/domain/quiz/repository/MockTestRepository.java
  src/main/java/dgu/sw/domain/quiz/repository/QuizRepository.java
  src/main/java/dgu/sw/domain/quiz/service/MockTestService.java
  src/main/java/dgu/sw/domain/quiz/service/MockTestServiceImpl.java
Labels: ✨ feature, 🐸 하은 작업

#102 [Feature] #101 - 모의고사 결과 조회 API 구현 및 불필요한 계산 제거
  src/main/java/dgu/sw/domain/quiz/controller/MockTestController.java
  src/main/java/dgu/sw/domain/quiz/converter/MockTestConverter.java
  src/main/java/dgu/sw/domain/quiz/dto/MockTestDTO.java
  src/main/java/dgu/sw/domain/quiz/entity/MockTest.java
  src/main/java/dgu/sw/domain/quiz/repository/MockTestRepository.java
  src/main/java/dgu/sw/domain/quiz/service/MockTestService.java
  src/main/java/dgu/sw/domain/quiz/service/MockTestServiceImpl.java
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
  src/main/java/dgu/sw/global/status/ErrorStatus.java
Labels: ✨ feature, :recycle: refactor, 🐸 하은 작업

#104 [Feature] #103 - 이전 모의고사 결과 조회 API 구현
  src/main/java/dgu/sw/domain/quiz/controller/MockTestController.java
  src/main/java/dgu/sw/domain/quiz/repository/MockTestRepository.java
  src/main/java/dgu/sw/domain/quiz/service/MockTestService.java
  src/main/java/dgu/sw/domain/quiz/service/MockTestServiceImpl.java
  src/main/java/dgu/sw/global/status/ErrorStatus.java
Labels: ✨ feature, 🐸 하은 작업

#105 [Feature] #89 - 비밀번호 변경, 이메일 인증 기능 구현
  src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
  src/main/java/dgu/sw/global/config/redis/RedisUtil.java
  src/main/java/dgu/sw/global/status/ErrorStatus.java
Labels: ✨ feature

#109 [Bug] #108 - 인증코드 관련 에러 중복 제거
  src/main/java/dgu/sw/global/status/ErrorStatus.java
Labels: :bug: fix

#111 [Refactor] #110 - 비밀번호 재설정용 인증코드 메일을 HTML 형식으로 발송
  src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
  src/main/java/dgu/sw/global/config/util/EmailService.java
Labels: :recycle: refactor, 🐸 하은 작업

#112 [Refactor] #107 - 카카오 SDK 기반 로그인 구현 및 신규 회원 여부 응답 추가
  src/main/java/dgu/sw/domain/auth/controller/AuthController.java
  src/main/java/dgu/sw/domain/auth/converter/AuthConverter.java
  src/main/java/dgu/sw/domain/auth/dto/AuthDTO.java
  src/main/java/dgu/sw/domain/auth/service/AuthService.java
  src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
Labels: :recycle: refactor, 🐸 하은 작업

#115 [Feature] #106 - 네이버 로그인 구현
  src/main/java/dgu/sw/domain/auth/controller/AuthController.java
  src/main/java/dgu/sw/domain/auth/converter/AuthConverter.java
  src/main/java/dgu/sw/domain/auth/dto/AuthDTO.java
  src/main/java/dgu/sw/domain/auth/service/AuthService.java
  src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
  src/main/java/dgu/sw/global/security/OAuthUtil.java
  src/main/resources/application.yml
Labels: ✨ feature, 🐸 하은 작업

#117 [Feature] #116 - 마이페이지 조회 API 구현
  src/main/java/dgu/sw/domain/user/controller/UserController.java
  src/main/java/dgu/sw/domain/user/converter/UserConverter.java
  src/main/java/dgu/sw/domain/user/dto/UserDTO.java
  src/main/java/dgu/sw/domain/user/service/UserService.java
  src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
Labels: ✨ feature, 🐸 하은 작업

#121 [Feature] #118 - 입사일 변경 API 구현 및 MyPageResponse에 Swagger용 @Schema 어노테이션 추가
  src/main/java/dgu/sw/domain/user/controller/UserController.java
  src/main/java/dgu/sw/domain/user/dto/UserDTO.java
  src/main/java/dgu/sw/domain/user/entity/User.java
  src/main/java/dgu/sw/domain/user/service/UserService.java
  src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
Labels: ✨ feature, 🐸 하은 작업

#125 [Bug] #124 - 동일 이메일 다른 소셜 로그인 시 에러 처리 및 에러코드 추가
  src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
  src/main/java/dgu/sw/global/status/ErrorStatus.java
Labels: :bug: fix, 🐸 하은 작업

#127 [Feature] #126 - 로그아웃 및 회원탈퇴 API 구현
  src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
  src/main/java/dgu/sw/domain/user/controller/UserController.java
  src/main/java/dgu/sw/domain/user/service/UserService.java
  src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
  src/main/java/dgu/sw/global/security/OAuthUtil.java
Labels: ✨ feature, 🐸 하은 작업

#128 [Feature] #90 - 구글 소셜 로그인 기능 구현
  src/main/java/dgu/sw/domain/auth/controller/AuthController.java
  src/main/java/dgu/sw/domain/auth/service/AuthService.java
  src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
  src/main/java/dgu/sw/global/security/OAuthUtil.java
  src/main/resources/application.yml
Labels: ✨ feature
