Repository 22-s/BE, pull requests merged in 2025-06, with the labels that each got.

#166 [Feature] #158 애플 로그인 구현
  src/main/java/dgu/sw/domain/auth/controller/AuthController.java
  src/main/java/dgu/sw/domain/auth/service/AuthService.java
  src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
  src/main/java/dgu/sw/global/security/OAuthUtil.java
  src/main/java/dgu/sw/global/status/ErrorStatus.java
Labels: ✨ feature, 🐸 하은 작업

#170 [Feature] #169 - 애플 로그인 회원 탈퇴 API 구현
  build.gradle
  src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
  src/main/java/dgu/sw/global/security/OAuthUtil.java
  src/main/resources/application.yml
Labels: ✨ feature, 🐸 하은 작업

#174 [Bug] #173 - 카테고리별 퀴즈 매핑 오류 해결
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
Labels: :bug: fix, 🐸 하은 작업

#176 [Refactor] #175 - Top 5 퀴즈 중 상태에 맞게 잠금(isLocked) 설정
  src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
Labels: :recycle: refactor, 🐸 하은 작업

#178 [Bug] - 모의고사 테스트 첫 시험인 경우 첫 점수로 점수 상승 반영
  src/main/java/dgu/sw/domain/quiz/service/MockTestServiceImpl.java
Labels: :bug: fix, 🐬 승우 작업
