Repository 22-s/BE, pull requests merged in 2025-07, with the labels that each got.

#185 [Feature] #146 - 알림 기능 구현
  src/main/java/dgu/sw/SwApplication.java
  src/main/java/dgu/sw/domain/notification/controller/NotificationController.java
  src/main/java/dgu/sw/domain/notification/dto/NotificationResponse.java
  src/main/java/dgu/sw/domain/notification/entity/Notification.java
  src/main/java/dgu/sw/domain/notification/repository/NotificationRepository.java
  src/main/java/dgu/sw/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/dgu/sw/domain/notification/service/NotificationService.java
  src/main/java/dgu/sw/domain/notification/service/NotificationServiceImpl.java
  src/main/java/dgu/sw/domain/user/controller/UserController.java
  src/main/java/dgu/sw/domain/user/dto/UserDTO.java
  src/main/java/dgu/sw/domain/user/entity/User.java
  src/main/java/dgu/sw/domain/user/service/UserService.java
  src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
  src/main/java/dgu/sw/global/exception/NotificationException.java
  src/main/java/dgu/sw/global/fcm/config/FirebaseInitializer.java
  src/main/java/dgu/sw/global/fcm/dto/FCMNotificationRequest.java
  src/main/java/dgu/sw/global/fcm/service/FCMService.java
  src/main/java/dgu/sw/global/status/ErrorStatus.java
  src/main/resources/application.yml
Labels: ✨ feature, 🐿️ 영신 작업

#191 [Fix] #190 - 프론트 도메인 대응을 위한 CORS 설정 allowedOriginPatterns로 변경
  src/main/java/dgu/sw/global/config/WebConfig.java
Labels: :bug: fix

#201 [Feature] #200 - 단어, 퀴즈, 매너 수정 API 구현
  src/main/java/dgu/sw/domain/admin/controller/AdminController.java
  src/main/java/dgu/sw/domain/admin/converter/AdminConverter.java
  src/main/java/dgu/sw/domain/admin/dto/AdminDTO.java
  src/main/java/dgu/sw/domain/admin/service/AdminService.java
  src/main/java/dgu/sw/domain/admin/service/AdminServiceImpl.java
  src/main/java/dgu/sw/domain/manner/entity/Manner.java
  src/main/java/dgu/sw/domain/quiz/entity/Quiz.java
  src/main/java/dgu/sw/domain/voca/entity/Voca.java
Labels: ✨ feature, 🐸 하은 작업

#207 [Fix] #206 - 퀴즈 레벨 추가 저장
  src/main/java/dgu/sw/domain/admin/converter/AdminConverter.java
Labels: :bug: fix, 🐸 하은 작업

#213 [Fix] #212 - user != null 여부를 체크하고 null인 경우 email, nickname은 그대로 null 반환
  src/main/java/dgu/sw/domain/admin/converter/AdminConverter.java
Labels: :bug: fix, 🐸 하은 작업

#214 [Refactor] #188 - fcm json file 로드 방법 변경
  src/main/java/dgu/sw/global/fcm/config/FirebaseInitializer.java
  src/main/resources/application.yml
Labels: :recycle: refactor, 🐿️ 영신 작업
